#!/bin/bash
keytool -genkeypair -v -keystore syahrul.keystore -alias syahrul -keyalg RSA -keysize 2048 -validity 10000
cd android && ./gradlew clean && ./gradlew assembleRelease
cd ..
jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore syahrul.keystore android/app/build/outputs/apk/app-release-unsigned.apk syahrul
/opt/android/build-tools/*/zipalign -v 4 android/app/build/outputs/apk/app-release-unsigned.apk android/app/build/outputs/apk/app-release.apk
